什么是 error？和 exception 有什么区别？

错误（异常）是一种“值”，属于正常逻辑返回（exception、error）。

  * Stuck in 70's
  * Errors just values

error 从 C 语言一脉相承，它完全抛弃了结构化异常上的一些技术进步。error
代表的是一种状态、一种“值”。比如在登录时，返回有正确、用户名不存在、密码错误、账户过期、账户禁用等各种状态，登录失败是很正常的状态，属于正常逻辑的一部分。

显然返回值不是错误而是一种值，所以错误是正常状态值，表达的是另一种状态。用错误来称呼异常不太合理，这两个词都代表着负面含义，但负面含义并不意味着就是错误。我们用
error 就是自定义一个 exception，无非 exception 是简单变量，error 是复合变量。

### 错误分类

通常情况下我们把错误分成两类，一种是可恢复的，一种是不可恢复的。

不可恢复的是彻彻底底的错误，比如连接数据库服务器网络有问题，或者数据库服务器宕机，这种情况下应用程序没有办法恢复，遇到这种不可恢复的错误，通常的做法是打印输出错误堆栈后，直接让应用程序直接崩溃，因为应用程序在这种情况下继续运行没有任何意义。最好方式让程序出错，并由监控程序对错误返回值进行处理，对管理员做出预警，管理员查看调用堆栈信息进行排查。

对于不可恢复的错误，使用什么样的策略去处理呢？如果应用程序什么都不做，一直等着错误消失，管理员不知道应用程序是正确还是错误。因为程序不死掉的话，管理员不知道应用程序是什么状态，或者需要依次排查服务器。

如果数据库服务器不是在同一个公司呢？或者监控程序只监控应用程序不监控数据库呢？所以应用程序是否抛出错误和依赖的资源是否被监控不是一回事，当遇到不可恢复错误的时候，最好的方式不是每隔一段时间去重试，而是让程序死掉，通过输出的调用堆栈信息和错误返回的状态码给监控系统明确的指示，管理员接收指示排查原因，当服务器恢复时，管理员可选择一种触发机制让应用程序启动执行。程序重试管理员根本不知道，打印信息和程序死掉对于监控系统完全是两种状态，除非监控系统专门针对打印信息做出处理。

可恢复性错误，比如说有一个除法，这种错误可以恢复的，最简单的，拦截这个错误通知调用方换一个参数。

### 错误处理

基本处理规则：

  * 将 error 和正常返回值分离，明确告知会有错误发生。
  * 与 exception 相比，error 不会中断执行流程。
  * 通过变量或类型匹配错误。
  * 总是检查所返回错误，避免后续逻辑出错。
  * 正常返回值和错误可能同时返回。（os.File.Read）

当一个函数同时返回两个值的时候，并没有一种规范来保证两个值是互斥的，例如 io 包的 Read
函数。没有统一的标准的情况下，可以写注释，可以通过代码的冗余来保证它的结果一致。

### 使用实例或类型判断错误类别

Go 语言不支持结构化异常时候，我们通常做法有几种，第一种使用变量，变量默认情况下要么实现 error 接口，要么实现自定义类型。判断返回值错误可以通过
`err == errVar` 判断某个具体的错误，`type(err) is IO` 判断属于哪一类的错误。第二种使用常量，尽可能避免使用魔法数字。

使用结构化异常的优点可在不同函数中拦截，对异常的处理很灵活，在调用堆栈任何一个环节使用装饰器捕获异常。比如 Web 应用通常是 Client 端发送
request，Web Server 对请求做 handler，执行 logic，可能有 db 最后返回结果。这样我们可以捕获错误信息，包括异常发送到
log 中，同时为了返回正常的状态，可以重新抛出异常。使用返回值的话只能在调用的地方做判断。

错误是正常的返回值，是一种很合理的状态值，是一种很合理的流程控制。我们可以利用错误控制程序执行流程，写代码时完全可以把错误当作正常逻辑来使用，当作正常流控制来使用。

### 检查错误值

    
    
    var errTest = errors.New("test")
    
    func test() error {
        return errTest
    }
    func main() {
        err := test()
        if err == errTest {
        }
    }
    

检查变量，而非内容。

对于错误值检查通常有几种方法，第一种把错误定义为变量，检查是不是指向同一个变量。

这种方式没必要单独建立类型，直接来检查。不要通过内容来匹配错误，因为内容是输出给调试人员看的辅助信息，不是用来匹配的。

    
    
    func test() error {
        return errors.New("test")
    }
    func main() {
        err := test()
        if err != nil && err.Error() == "test" {
        }
    }
    

有很多人直接 errors.New，通过内容来判断错误。任何时候不要通过内容来匹配。

### 检查错误类型

    
    
    func main() {
        err := test()
        if _, ok := err.(ErrSome); ok {
        }
        switch err.(type) {
        case nil: // no error
        case ErrSome: // do something...
        default: // unknown error
        }
    }
    

通过自定义类型匹配处理方式。

通过检查错误类型，错误是哪一类错误。需要定义类型，指明是哪一类错误，这是结构化异常最常见做法，抛出哪一类错误。

检查错误有两种方式。

  * 第一种通过类型转换，把错误转化成某个具体的类型。
  * 第二种通过 switch 语句处理。nil 表示没有错误，是某一类错误进行处理，或者不知道哪种错误。

### 常量错误值

    
    
    type Error string
    
    func (e Error) Error() string { return string(e) }
    
    const ErrEOF = Error("EOF")
    
    func test() error {
        return ErrEOF
    }
    func main() {
        err := test()
        println(err == Error("EOF"))
    }
    

通过“字符串”实现常量值。

有一种不推荐的写法，基于字符串来定义类型并实现 error
接口。使用常量定义错误，常量最终会被展开，也意味着从变量匹配变成内容匹配。匹配内容从设计上来说和设计理念不相符。

使用全局变量定义错误实际上非常危险，可能被拦截修改。

